name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get commits
        run: |
          COMMITS=${{ github.event.commits }}
          
          echo Length =  ${#COMMITS[@]}
          
          echo Message = ${{ github.event.commits[0].message }}

          for c in "${{ github.event.commits }}"
          do
             echo "test..."
             echo "$c"
          done
     
