name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Get commits
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              if(commit.author.name == 'hmmachadocx') {
                return true;
              }
            }
            
            return false;
            
      - name: Get result
        run: echo "THE RESULT IS = ${{steps.set-result.outputs.result}}"
        
      - name: Call release
        if: steps.set-result.outputs.result == true
        run: echo "The release workflow will be called..."
          
          
     
