name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get commits
        run: |
          A=${{ github.event.commits }}
          echo $A
          
          echo ====================================================
        
          B=(${{ github.event.commits }})
          echo $B
          
          echo ====================================================
          
          C=${{toJson(github.event.commits)}}
          echo $C
          
          
          
          #for i in "${COMMITS[@]}"
          #do
          #    echo $i['author']
          #done
     
