name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  #check-dependabot-commits:    
  #  name: Check if dependabot commits exist
  #  outputs:
  #    isDependabot: ${{ steps.check-dependabot.outputs.dependabotExists }}
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Check if dependabot commits exist
  #    id: check-dependabot
  #    env:
  #      GITHUB_CONTEXT: ${{ toJson(github) }}
  #    run: echo "dependabotExists=$(echo $GITHUB_CONTEXT | jq '.event.commits[].author | any(. == "dependabot[bot]")')" >> $GITHUB_OUTPUT
      
  #call-release:
  #  runs-on: ubuntu-latest
  #  needs: check-dependabot-commits
  #  steps:
  #    - name: cenas
  #      if: true
  #      run: | 
  #        echo "RUN!!!"
  #        echo needs.check-dependabot-commits.outputs.isDependabot == false
  #        echo needs.check-dependabot-commits.outputs.isDependabot == true
  #        echo ${{ needs.check-dependabot-commits.outputs.isDependabot }} == false
  #        echo ${{ needs.check-dependabot-commits.outputs.isDependabot }} == true
  #        echo ${{ needs.check-dependabot-commits.outputs.isDependabot }} == 'false'
  #        echo ${{ needs.check-dependabot-commits.outputs.isDependabot }} == 'true'
  #        echo ${{ needs.check-dependabot-commits.outputs.isDependabot}}
  #        CHECK="$(boolean "${{ needs.check-dependabot-commits.outputs.isDependabot }}")"
  #        echo "CHECK = $CHECK"
  #        echo "==========================="
          
  #        echo env.dependabotExists
  #        echo env.dependabotExists == true
  #        echo env.dependabotExists == 'true'
  #        echo env.dependabotExists == false
  #        echo env.dependabotExists == 'false'
          
  check-dependabot-commits:
    outputs:
      isDependabot: ${{ steps.set-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependabot commits exist
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              if(commit.author.name == 'dependabot[bot]') {
                return true;
              }
            }
            
            return false;
          
          
  call-release-test:
    runs-on: ubuntu-latest
    needs: check-dependabot-commits
    steps:
      - name: cenas
        if: true
        run: | 
          echo "RUN!!!"
          Y=${{needs.check-dependabot-commits.outputs.isDependabot == false}} 
          echo RESULT = ${Y}
          echo ${{needs.check-dependabot-commits.outputs.isDependabot}}
          
  #nightly:
  #  needs: check-dependabot-commits
  #  if: ${{needs.check-dependabot-commits.outputs.isDependabot}} == 'false'
  #  uses: hugomachadoOrg/fork-ast-vscode-extension/.github/workflows/release.yml@main
  #  secrets: inherit
 
          
          
     
