name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  check-dependabot-commits:
    outputs:
      isDependabot: ${{ steps.set-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependabot commits exist
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              if(commit.author.name == 'hmmachadocx') {
                return true;
              }
            }
            
            return false;
          
  nightly:
    runs-on: ubuntu-latest
    needs: check-dependabot-commits
    steps:
      - name: Echo cenas
        run: echo ${{needs.check-dependabot-commits.outputs.isDependabot}}

 
          
          
     
