name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  #check-dependabot-commits-a:
  #  outputs:
  #    isDependabot: ${{ steps.set-result.outputs.result }}
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check if dependabot commits exist
  #      uses: actions/github-script@v6
  #      id: set-result
  #      with:
  #        script: |
  #          const commits = ${{ toJSON(github.event.commits) }}
  #          for (const commit of commits) {
  #            if(commit.author.name == 'dependabot[bot]') {
  #              return true;
  #            }
  #          }
            
  #          return false;
            
      #- name: Contains dependabot
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #  run: |
      #    echo "$GITHUB_CONTEXT"
          #echo "RUNNED !!!"
          #echo '${{ toJSON(github.event.commits) }}'
          #echo '${{ toJSON(github.event.commits) }}' | jq ".[0].author"
          #myJson=${{ toJSON(github.event.commits) }}
          #echo $myJson
          #aaa=$( echo "${{ toJSON(github.event.commits) }}" | jq '.event.commits[].author | any(. == "hmmachadocx")' )
          #echo '${{ toJSON(github.event.commits) }}' | jq '.event.commits[].author | any(. == "hmmachadocx")'
          
  check-dependabot-commits:    
    name: Check if dependabot commits exist
    outputs:
      isDependabot: ${{ steps.check-dependabot.outputs.dependabotExists }}
    runs-on: ubuntu-latest
    steps:
    - name: Check if dependabot commits exist
      id: check-dependabot
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        #MY_VAR=$(echo $GITHUB_CONTEXT | jq '.event.commits[].author | any(. == "hmmachadocx")')
        echo "dependabotExists=$(echo $GITHUB_CONTEXT | jq '.event.commits[].author | any(. == "hmmachadocx")')" >> $GITHUB_OUTPUT
        
        
      
  call-release:
    runs-on: ubuntu-latest
    needs: check-dependabot-commits
    steps:
      - run: echo ${{needs.check-dependabot-commits.outputs.isDependabot}}
          
  #nightly:
  #  needs: check-dependabot-commits
  #  if: ${{needs.check-dependabot-commits.outputs.isDependabot}} == 'false'
  #  uses: hugomachadoOrg/fork-ast-vscode-extension/.github/workflows/release.yml@main
  #  secrets: inherit
 
          
          
     
