name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  check-dependabot-commits:
    outputs:
      isDependabot: ${{ steps.set-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependabot commits exist
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              if(commit.author.name == 'dependabot[bot]') {
                return true;
              }
            }
            
            return false;
            
      #- name: Contains dependabot
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #  run: |
      #    echo "$GITHUB_CONTEXT"
          #echo "RUNNED !!!"
          #echo '${{ toJSON(github.event.commits) }}'
          #echo '${{ toJSON(github.event.commits) }}' | jq ".[0].author"
          #myJson=${{ toJSON(github.event.commits) }}
          #echo $myJson
          #aaa=$( echo "${{ toJSON(github.event.commits) }}" | jq '.event.commits[].author | any(. == "hmmachadocx")' )
          #echo '${{ toJSON(github.event.commits) }}' | jq '.event.commits[].author | any(. == "hmmachadocx")'
          
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT" | jq '.event.commits[].author | any(. == "hmmachadocx")'
          
  #nightly:
  #  needs: check-dependabot-commits
  #  if: ${{needs.check-dependabot-commits.outputs.isDependabot}} == 'false'
  #  uses: hugomachadoOrg/fork-ast-vscode-extension/.github/workflows/release.yml@main
  #  secrets: inherit
 
          
          
     
