name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependabot commits exist
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              if(commit.author.name == 'dependabot[bot]') {
                return true;
              }
            }
            
            return false;

      - name: Call release
        if: steps.set-result.outputs.result == 'true'
        run: echo "The release workflow will be called..."
          
          
     
