name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write

on:
  schedule:
  - cron: 0 0 * * 0 # Every Sunday at 00:00

jobs:
  nightly:
    uses: hugomachadoOrg/fork-ast-vscode-extension/.github/workflows/release.yml@main
    secrets: inherit
