name: VSCode Release

on:
  workflow_call:
    inputs:
      jsTag:
        description: 'JS Wrapper tag name'
        required: false
        type: string
        default: nightly
      vscodeTag:
        description: 'Tag name (ignored if not dev build)'
        required: false
        type: string
        default: nightly
      dev:
        description: 'Is dev build'
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      jsTag:
        description: 'JSW tag name (ignored if not dev build)'
        required: false
      vscodeTag:
        description: 'Tag name (ignored if not dev build)'
        required: false
      dev:
        description: 'Is dev build'
        required: false
        default: true
        type: boolean

jobs:
  delete:
    uses: hugomachadoOrg/fork-ast-vscode-extension/.github/workflows/delete-dev-releases.yml@main
    with:
      tag: ${{ inputs.vscodeTag }}
    secrets: inherit
    if: inputs.dev
  release:
    runs-on: ubuntu-latest
    steps:

      # CHECKOUT PROJECT
      - name: Checkout
        uses: actions/checkout@v3.5.2

      # GIT CONFIGURATION
      - run: |
          git config user.name vscode-releases
          git config user.email vscode-releases@github.com

      # AUTHENTICATE TO GITHUB PACKAGE REGISTRY
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      # SETUP NODE
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      # GET TAG NAME
      - name: Generate Tag name
        run: |
          if [ ${{ inputs.dev }} == true ]; then
            echo "TAG_NAME=$(npm version prerelease --preid=${{ inputs.vscodeTag }} --no-git-tag-version --allow-same-version)" >> $GITHUB_ENV
          else
            echo "TAG_NAME=$(npm version patch)" >> $GITHUB_ENV
          fi
          
      - name: Install dependencies
        run: npm install
        
      - name: Get and install JS Wrapper if provided by user
        if: inputs.dev == true && inputs.jsTag != ''
        run: |
          echo "Getting js wrapper ${{inputs.jsTag}} version..."

          JS_VERSION_NAME=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/CheckmarxDev/packages/npm/ast-cli-javascript-wrapper/versions | jq '.[]|select(.name | contains("-${{inputs.jsTag}}.0"))|.name' | tr -d '"')
                              
          if [ ${JS_VERSION_NAME} != '' ]; then
            echo "Install JS Wrapper version  ${JS_VERSION_NAME}"
            npm install "@checkmarxdev/ast-cli-javascript-wrapper@"${JS_VERSION_NAME}
          else
            echo "JS wrapper with version ${JS_VERSION_NAME} not found"
          fi
          
      - name: Install VSCE
        run: npm install -g vsce

      - name: Package .vsix file
        run: |
          if [ ${{ inputs.dev }} == true ]; then
            vsce package --pre-release
          else
            vsce package
          fi
          
          TAG_NAME=${{env.TAG_NAME}}
          echo TAG NAME = ${TAG_NAME}
          echo "VSIX_TAG_NAME=${TAG_NAME:1}" >> $GITHUB_ENV
        
      # PUSH TAGS IF IT IS A RELEASE
      - name: Push tag if release
        if: inputs.dev == false
        run: git push && git push --tags
 
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.TAG_NAME}}
          generate_release_notes: true
          files: fork-ast-results-${{env.VSIX_TAG_NAME}}.vsix
          prerelease: ${{ inputs.dev }}
          
          
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{env.TAG_NAME}} # This may also be of the form 'refs/tags/staging'
          
          # Pick one of:
          # 3. multiple names/globs, one per line
          assets: '*.zip'
         
      #- name: Upload source with changes to workflow run
      #  if: inputs.dev == true
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{env.TAG_NAME}}
      #    path: |
      #      ./
      #      !node_modules

      #- name: Publish
      #  env:
      #    MARKET_TOKEN: ${{ secrets.MARKET_TOKEN }}
      #  if: env.MARKET_TOKEN != null
      #  run: vsce publish -p ${{ env.MARKET_TOKEN }}
